CREATE TABLE CUSTOMER
(
  ID NUMBER PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR2(4000),
  LAST_NAME VARCHAR2(4000)
);
ALTER TABLE CUSTOMER
ADD CONSTRAINT unique_ID UNIQUE (ID);

CREATE SEQUENCE SEQ_CUSTOMER MINVALUE 1 MAXVALUE 99999999999 NOCACHE;
